# Generated by Django 3.1.7 on 2021-07-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210729_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceanswer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_in_service_answer', to='service.service'),
        ),
    ]
