# Generated by Django 3.1.7 on 2021-08-09 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210730_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.URLField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
