# Generated by Django 3.1.7 on 2021-09-09 07:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210809_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='requirement',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
