# Generated by Django 3.1.7 on 2021-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210909_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
