# Generated by Django 3.1.7 on 2021-09-15 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210915_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
