# Generated by Django 3.1.7 on 2021-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
