# Generated by Django 3.1.7 on 2021-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210803_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Employer', 'Employer'), ('Freelancer', 'Freelancer')], default='Employer', max_length=25, null=True),
        ),
    ]
