# Generated by Django 3.1.7 on 2021-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210804_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='f_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
