# Generated by Django 3.1.7 on 2021-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210823_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
