# Generated by Django 3.1.7 on 2021-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
