# Generated by Django 3.1.7 on 2021-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='study_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
