# Generated by Django 3.1.7 on 2021-07-13 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Rising Talent', 'Rising Talent'), ('Intermediate', 'Intermediate'), ('Ultra Pro', 'Ultra Pro')], default='Rising Talent', max_length=25)),
                ('english_level', models.CharField(choices=[('Fluent', 'Fluent'), ('Better', 'Better')], default='Better', max_length=25)),
                ('project_level', models.CharField(choices=[('One Time', 'One Time'), ('Ongoing', 'Ongoing'), ('Complex', 'Complex')], default='One Time', max_length=25)),
                ('duration', models.CharField(choices=[('0-1 Month', '0-1 Month'), ('1-2 Months', '1-2 Months'), ('2-4 Months', '2-4 Months'), ('4-6 Months', '4-6 Months'), ('6 Months to 1 Year', '6 Months to 1 Year'), ('1 Year +', '1 Year +')], default='0-1 Month', max_length=25)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.CharField(choices=[('70 - 80', '70 - 80'), ('80 - 90', '80 - 90'), ('90 +', '90 +'), ('Any', 'Any')], default='Any', max_length=25)),
                ('budget_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Per Hour', 'Per Hour')], default='Fixed', max_length=25)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_in_job', to='category_management.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_in_job', to='category_management.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
