# Generated by Django 3.1.7 on 2021-07-14 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0001_initial'),
        ('job', '0003_auto_20210714_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_in_job', to='category_management.category'),
        ),
    ]
