# Generated by Django 3.1.7 on 2021-08-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('job', '0005_auto_20210809_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_in_job_skill', to='user_profile.skill'),
        ),
    ]
