# Generated by Django 3.1.7 on 2021-08-12 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210809_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
