# Generated by Django 3.1.7 on 2021-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='english_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Native', 'Native'), ('Fluent', 'Fluent')], default='Basic', max_length=25),
        ),
    ]
