# Generated by Django 3.1.7 on 2021-08-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210823_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobquestions',
            name='file',
        ),
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
