# Generated by Django 3.1.7 on 2021-08-09 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0004_auto_20210714_0530'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(blank=True, choices=[('0-1 Month', '0-1 Month'), ('1-2 Months', '1-2 Months'), ('2-4 Months', '2-4 Months'), ('4-6 Months', '4-6 Months'), ('6 Months to 1 Year', '6 Months to 1 Year'), ('1 Year +', '1 Year +')], max_length=100, null=True)),
                ('paid_type', models.CharField(choices=[('Project', 'Project'), ('Mile Stone', 'Mile Stone')], default='Project', max_length=30)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_in_bid', to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_bid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidMileStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_in_bid_mile_stone', to='bid.bid')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_in_bid_mile_stone', to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_bid_mile_stone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
