# Generated by Django 3.1.7 on 2021-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidmilestone',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
