# Generated by Django 3.1.7 on 2021-09-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_jobanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanswer',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_in_job_answer', to='bid.bid'),
            preserve_default=False,
        ),
    ]
