# Generated by Django 3.1.7 on 2021-09-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_jobanswer_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidmilestone',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50, null=True),
        ),
    ]
