# Generated by Django 3.1.7 on 2021-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0008_auto_20210916_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
