# Generated by Django 3.1.7 on 2021-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0009_auto_20210916_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
